apiVersion: apps/v1
kind: Deployment
metadata:
  name: netnumber-deployment
  labels:
    app: netnumber
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netnumber
  template:
    metadata:
      labels:
        app: netnumber
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "worker_in"
                    operator: "In"
                    values:
                      - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "oam-broker"
              topologyKey: "kubernetes.io/hostname"       
      containers:
        - name: oam-broker
          image: oam-broker.jpg
          ports: 
            - containerPort: 80
          env:
            - name: oam-broker-env
              value: "production"
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


